apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dpl
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: '@Aa123456'
          image: mcr.microsoft.com/mssql/server:2019-latest
          name: db
          ports:
            - containerPort: 1433
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: db
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    app: db
