apiVersion: apps/v1
kind: Deployment
metadata:
  name: partners-api-dpl 
  labels:
    app: partners-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partners-api
  template:
    metadata:
      labels:
        app: partners-api
        version: v1
    spec:
      containers:
      - name: partners-api
        image: mehdihadeli/partners.api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: partners-api-svc-v1
  labels:
    app: partners-api
spec:
  type: NodePort
  selector:
    app: partners-api
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
    name: http