version: '3'
services: 
  partners.api:
    container_name: partners.api
    ports:
        - '5000:5000'
    restart: on-failure
    image: partners.api:latest
    # environment:   
    #   - TZ=Asia/Tehran
    #   - "ConnectionStrings__OrdersConnection=Server=db;Database=OrderDB;User=sa;Password=@Aa123456;MultipleActiveResultSets=true"
    #   - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
    #   - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    #   - "ASPNETCORE_URLS=https://+:5001;http://+:5000"
    build: 
      context: ../../src
      dockerfile: Api.Dockerfile
    depends_on:
      - db
  db:
    container_name: sqldb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@Aa123456"
      ACCEPT_EULA: "Y"
